version: "3"

services:
  app1:
    build: .
    expose:
      - 3000

  app2:
    build: .
    expose:
      - 3000

  load_balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
